[package]
name = "lox-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ilox"
path = "src/interpreter/main.rs"
test = true
bench = false

[dependencies]
anyhow = "1.0.45"
thiserror = "1.0.30"
dyn-clone = "1.0.4"
